package structures;

public enum NodeType {
    TERMINAL, QUERY, COLUMN_NAMES, COLUMN_NAMES_CONT, WHERE_PART, CONDITION, FIELD_VALUE,
    SKIP_LIMIT_PART, SKIP_PART, LIMIT_PART, ABS_SKIP_PART, ABS_LIMIT_PART
}
